baseURL = "https://axcs.netlify.app/"
languageCode = "ja-JP"
title = "How to use ArxCharacterShaders"
theme = "hugo-theme-learn"
canonifyurls = true

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
    # Disable search function. It will hide search bar
  disableSearch = true

[blackfriday]
  hrefTargetBlank = true