baseURL = "https://synqark.github.io/AXCS_Docs/"
languageCode = "ja-JP"
title = "How to use ArxCharacterShaders"
theme = "hugo-theme-learn"
canonifyurls = true

[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
  # themeVariant = "blue"
  disableSearch = false

[blackfriday]
  hrefTargetBlank = true