baseURL = "https://synqark.github.io/AXCS_Docs/"
languageCode = "ja-JP"
title = "How to use ArxCharacterShaders"
theme = "learn-20201214"
canonifyurls = true
[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
# Change default color scheme with a variant one. Can be "red", "blue", "green".
  # themeVariant = "blue"
  disableSearch = false
  disableNextPrev = true
disableInlineCopyToClipBoard = true
[blackfriday]
  hrefTargetBlank = true